// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/activities_v1.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorDescription struct {
	Type                 string            `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Category             string            `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Code                 string            `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	CorrelationId        string            `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Status               string            `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Message              string            `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Cause                string            `protobuf:"bytes,7,opt,name=cause,proto3" json:"cause,omitempty"`
	StackTrace           string            `protobuf:"bytes,8,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	Details              map[string]string `protobuf:"bytes,9,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ErrorDescription) Reset()         { *m = ErrorDescription{} }
func (m *ErrorDescription) String() string { return proto.CompactTextString(m) }
func (*ErrorDescription) ProtoMessage()    {}
func (*ErrorDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_9682ce189d08eec3, []int{0}
}

func (m *ErrorDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorDescription.Unmarshal(m, b)
}
func (m *ErrorDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorDescription.Marshal(b, m, deterministic)
}
func (m *ErrorDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorDescription.Merge(m, src)
}
func (m *ErrorDescription) XXX_Size() int {
	return xxx_messageInfo_ErrorDescription.Size(m)
}
func (m *ErrorDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorDescription.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorDescription proto.InternalMessageInfo

func (m *ErrorDescription) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ErrorDescription) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *ErrorDescription) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ErrorDescription) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *ErrorDescription) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ErrorDescription) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ErrorDescription) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

func (m *ErrorDescription) GetStackTrace() string {
	if m != nil {
		return m.StackTrace
	}
	return ""
}

func (m *ErrorDescription) GetDetails() map[string]string {
	if m != nil {
		return m.Details
	}
	return nil
}

type PagingParams struct {
	Skip                 int64    `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Take                 int32    `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	Total                bool     `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PagingParams) Reset()         { *m = PagingParams{} }
func (m *PagingParams) String() string { return proto.CompactTextString(m) }
func (*PagingParams) ProtoMessage()    {}
func (*PagingParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_9682ce189d08eec3, []int{1}
}

func (m *PagingParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagingParams.Unmarshal(m, b)
}
func (m *PagingParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagingParams.Marshal(b, m, deterministic)
}
func (m *PagingParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagingParams.Merge(m, src)
}
func (m *PagingParams) XXX_Size() int {
	return xxx_messageInfo_PagingParams.Size(m)
}
func (m *PagingParams) XXX_DiscardUnknown() {
	xxx_messageInfo_PagingParams.DiscardUnknown(m)
}

var xxx_messageInfo_PagingParams proto.InternalMessageInfo

func (m *PagingParams) GetSkip() int64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *PagingParams) GetTake() int32 {
	if m != nil {
		return m.Take
	}
	return 0
}

func (m *PagingParams) GetTotal() bool {
	if m != nil {
		return m.Total
	}
	return false
}

type Reference struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reference) Reset()         { *m = Reference{} }
func (m *Reference) String() string { return proto.CompactTextString(m) }
func (*Reference) ProtoMessage()    {}
func (*Reference) Descriptor() ([]byte, []int) {
	return fileDescriptor_9682ce189d08eec3, []int{2}
}

func (m *Reference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reference.Unmarshal(m, b)
}
func (m *Reference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reference.Marshal(b, m, deterministic)
}
func (m *Reference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reference.Merge(m, src)
}
func (m *Reference) XXX_Size() int {
	return xxx_messageInfo_Reference.Size(m)
}
func (m *Reference) XXX_DiscardUnknown() {
	xxx_messageInfo_Reference.DiscardUnknown(m)
}

var xxx_messageInfo_Reference proto.InternalMessageInfo

func (m *Reference) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Reference) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Reference) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PartyActivity struct {
	// Identification
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Identification fields
	Time  string     `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Type  string     `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Party *Reference `protobuf:"bytes,4,opt,name=party,proto3" json:"party,omitempty"`
	// References objects (notes, goals, etc.)
	RefItem    *Reference   `protobuf:"bytes,5,opt,name=ref_item,json=refItem,proto3" json:"ref_item,omitempty"`
	RefParents []*Reference `protobuf:"bytes,6,rep,name=ref_parents,json=refParents,proto3" json:"ref_parents,omitempty"`
	RefParty   *Reference   `protobuf:"bytes,7,opt,name=ref_party,json=refParty,proto3" json:"ref_party,omitempty"`
	// Other details like % of progress or new status
	Details              map[string]string `protobuf:"bytes,8,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	OrgId                string            `protobuf:"bytes,9,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PartyActivity) Reset()         { *m = PartyActivity{} }
func (m *PartyActivity) String() string { return proto.CompactTextString(m) }
func (*PartyActivity) ProtoMessage()    {}
func (*PartyActivity) Descriptor() ([]byte, []int) {
	return fileDescriptor_9682ce189d08eec3, []int{3}
}

func (m *PartyActivity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartyActivity.Unmarshal(m, b)
}
func (m *PartyActivity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartyActivity.Marshal(b, m, deterministic)
}
func (m *PartyActivity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartyActivity.Merge(m, src)
}
func (m *PartyActivity) XXX_Size() int {
	return xxx_messageInfo_PartyActivity.Size(m)
}
func (m *PartyActivity) XXX_DiscardUnknown() {
	xxx_messageInfo_PartyActivity.DiscardUnknown(m)
}

var xxx_messageInfo_PartyActivity proto.InternalMessageInfo

func (m *PartyActivity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PartyActivity) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *PartyActivity) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PartyActivity) GetParty() *Reference {
	if m != nil {
		return m.Party
	}
	return nil
}

func (m *PartyActivity) GetRefItem() *Reference {
	if m != nil {
		return m.RefItem
	}
	return nil
}

func (m *PartyActivity) GetRefParents() []*Reference {
	if m != nil {
		return m.RefParents
	}
	return nil
}

func (m *PartyActivity) GetRefParty() *Reference {
	if m != nil {
		return m.RefParty
	}
	return nil
}

func (m *PartyActivity) GetDetails() map[string]string {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *PartyActivity) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

type PartyActivityPage struct {
	Total                int64            `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*PartyActivity `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PartyActivityPage) Reset()         { *m = PartyActivityPage{} }
func (m *PartyActivityPage) String() string { return proto.CompactTextString(m) }
func (*PartyActivityPage) ProtoMessage()    {}
func (*PartyActivityPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_9682ce189d08eec3, []int{4}
}

func (m *PartyActivityPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartyActivityPage.Unmarshal(m, b)
}
func (m *PartyActivityPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartyActivityPage.Marshal(b, m, deterministic)
}
func (m *PartyActivityPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartyActivityPage.Merge(m, src)
}
func (m *PartyActivityPage) XXX_Size() int {
	return xxx_messageInfo_PartyActivityPage.Size(m)
}
func (m *PartyActivityPage) XXX_DiscardUnknown() {
	xxx_messageInfo_PartyActivityPage.DiscardUnknown(m)
}

var xxx_messageInfo_PartyActivityPage proto.InternalMessageInfo

func (m *PartyActivityPage) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PartyActivityPage) GetData() []*PartyActivity {
	if m != nil {
		return m.Data
	}
	return nil
}

// The request message containing the party_activity page request.
type PartyActivityPageRequest struct {
	CorrelationId        string            `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Filter               map[string]string `protobuf:"bytes,2,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Paging               *PagingParams     `protobuf:"bytes,3,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PartyActivityPageRequest) Reset()         { *m = PartyActivityPageRequest{} }
func (m *PartyActivityPageRequest) String() string { return proto.CompactTextString(m) }
func (*PartyActivityPageRequest) ProtoMessage()    {}
func (*PartyActivityPageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9682ce189d08eec3, []int{5}
}

func (m *PartyActivityPageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartyActivityPageRequest.Unmarshal(m, b)
}
func (m *PartyActivityPageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartyActivityPageRequest.Marshal(b, m, deterministic)
}
func (m *PartyActivityPageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartyActivityPageRequest.Merge(m, src)
}
func (m *PartyActivityPageRequest) XXX_Size() int {
	return xxx_messageInfo_PartyActivityPageRequest.Size(m)
}
func (m *PartyActivityPageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PartyActivityPageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PartyActivityPageRequest proto.InternalMessageInfo

func (m *PartyActivityPageRequest) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *PartyActivityPageRequest) GetFilter() map[string]string {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *PartyActivityPageRequest) GetPaging() *PagingParams {
	if m != nil {
		return m.Paging
	}
	return nil
}

// The response message containing the party_activity page response
type PartyActivityPageReply struct {
	Error                *ErrorDescription  `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Page                 *PartyActivityPage `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PartyActivityPageReply) Reset()         { *m = PartyActivityPageReply{} }
func (m *PartyActivityPageReply) String() string { return proto.CompactTextString(m) }
func (*PartyActivityPageReply) ProtoMessage()    {}
func (*PartyActivityPageReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9682ce189d08eec3, []int{6}
}

func (m *PartyActivityPageReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartyActivityPageReply.Unmarshal(m, b)
}
func (m *PartyActivityPageReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartyActivityPageReply.Marshal(b, m, deterministic)
}
func (m *PartyActivityPageReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartyActivityPageReply.Merge(m, src)
}
func (m *PartyActivityPageReply) XXX_Size() int {
	return xxx_messageInfo_PartyActivityPageReply.Size(m)
}
func (m *PartyActivityPageReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PartyActivityPageReply.DiscardUnknown(m)
}

var xxx_messageInfo_PartyActivityPageReply proto.InternalMessageInfo

func (m *PartyActivityPageReply) GetError() *ErrorDescription {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *PartyActivityPageReply) GetPage() *PartyActivityPage {
	if m != nil {
		return m.Page
	}
	return nil
}

// The request message containing the party_activity page request.
type PartyActivityLogRequest struct {
	CorrelationId        string         `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Activity             *PartyActivity `protobuf:"bytes,2,opt,name=activity,proto3" json:"activity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PartyActivityLogRequest) Reset()         { *m = PartyActivityLogRequest{} }
func (m *PartyActivityLogRequest) String() string { return proto.CompactTextString(m) }
func (*PartyActivityLogRequest) ProtoMessage()    {}
func (*PartyActivityLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9682ce189d08eec3, []int{7}
}

func (m *PartyActivityLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartyActivityLogRequest.Unmarshal(m, b)
}
func (m *PartyActivityLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartyActivityLogRequest.Marshal(b, m, deterministic)
}
func (m *PartyActivityLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartyActivityLogRequest.Merge(m, src)
}
func (m *PartyActivityLogRequest) XXX_Size() int {
	return xxx_messageInfo_PartyActivityLogRequest.Size(m)
}
func (m *PartyActivityLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PartyActivityLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PartyActivityLogRequest proto.InternalMessageInfo

func (m *PartyActivityLogRequest) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *PartyActivityLogRequest) GetActivity() *PartyActivity {
	if m != nil {
		return m.Activity
	}
	return nil
}

// The response message containing the party_activity object response
type PartyActivityObjectReply struct {
	Error                *ErrorDescription `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Activity             *PartyActivity    `protobuf:"bytes,2,opt,name=activity,proto3" json:"activity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PartyActivityObjectReply) Reset()         { *m = PartyActivityObjectReply{} }
func (m *PartyActivityObjectReply) String() string { return proto.CompactTextString(m) }
func (*PartyActivityObjectReply) ProtoMessage()    {}
func (*PartyActivityObjectReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9682ce189d08eec3, []int{8}
}

func (m *PartyActivityObjectReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartyActivityObjectReply.Unmarshal(m, b)
}
func (m *PartyActivityObjectReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartyActivityObjectReply.Marshal(b, m, deterministic)
}
func (m *PartyActivityObjectReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartyActivityObjectReply.Merge(m, src)
}
func (m *PartyActivityObjectReply) XXX_Size() int {
	return xxx_messageInfo_PartyActivityObjectReply.Size(m)
}
func (m *PartyActivityObjectReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PartyActivityObjectReply.DiscardUnknown(m)
}

var xxx_messageInfo_PartyActivityObjectReply proto.InternalMessageInfo

func (m *PartyActivityObjectReply) GetError() *ErrorDescription {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *PartyActivityObjectReply) GetActivity() *PartyActivity {
	if m != nil {
		return m.Activity
	}
	return nil
}

// The request message containing the party_activity page request.
type PartyActivityBatchRequest struct {
	CorrelationId        string           `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Activities           []*PartyActivity `protobuf:"bytes,2,rep,name=activities,proto3" json:"activities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PartyActivityBatchRequest) Reset()         { *m = PartyActivityBatchRequest{} }
func (m *PartyActivityBatchRequest) String() string { return proto.CompactTextString(m) }
func (*PartyActivityBatchRequest) ProtoMessage()    {}
func (*PartyActivityBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9682ce189d08eec3, []int{9}
}

func (m *PartyActivityBatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartyActivityBatchRequest.Unmarshal(m, b)
}
func (m *PartyActivityBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartyActivityBatchRequest.Marshal(b, m, deterministic)
}
func (m *PartyActivityBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartyActivityBatchRequest.Merge(m, src)
}
func (m *PartyActivityBatchRequest) XXX_Size() int {
	return xxx_messageInfo_PartyActivityBatchRequest.Size(m)
}
func (m *PartyActivityBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PartyActivityBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PartyActivityBatchRequest proto.InternalMessageInfo

func (m *PartyActivityBatchRequest) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *PartyActivityBatchRequest) GetActivities() []*PartyActivity {
	if m != nil {
		return m.Activities
	}
	return nil
}

// The request message containing the party_activity page request.
type PartyActivityDeleteRequest struct {
	CorrelationId        string            `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Filter               map[string]string `protobuf:"bytes,2,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PartyActivityDeleteRequest) Reset()         { *m = PartyActivityDeleteRequest{} }
func (m *PartyActivityDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*PartyActivityDeleteRequest) ProtoMessage()    {}
func (*PartyActivityDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9682ce189d08eec3, []int{10}
}

func (m *PartyActivityDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartyActivityDeleteRequest.Unmarshal(m, b)
}
func (m *PartyActivityDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartyActivityDeleteRequest.Marshal(b, m, deterministic)
}
func (m *PartyActivityDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartyActivityDeleteRequest.Merge(m, src)
}
func (m *PartyActivityDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_PartyActivityDeleteRequest.Size(m)
}
func (m *PartyActivityDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PartyActivityDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PartyActivityDeleteRequest proto.InternalMessageInfo

func (m *PartyActivityDeleteRequest) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *PartyActivityDeleteRequest) GetFilter() map[string]string {
	if m != nil {
		return m.Filter
	}
	return nil
}

// The response message containing the party_activity object response
type PartyActivityOnlyErrorReply struct {
	Error                *ErrorDescription `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PartyActivityOnlyErrorReply) Reset()         { *m = PartyActivityOnlyErrorReply{} }
func (m *PartyActivityOnlyErrorReply) String() string { return proto.CompactTextString(m) }
func (*PartyActivityOnlyErrorReply) ProtoMessage()    {}
func (*PartyActivityOnlyErrorReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9682ce189d08eec3, []int{11}
}

func (m *PartyActivityOnlyErrorReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartyActivityOnlyErrorReply.Unmarshal(m, b)
}
func (m *PartyActivityOnlyErrorReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartyActivityOnlyErrorReply.Marshal(b, m, deterministic)
}
func (m *PartyActivityOnlyErrorReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartyActivityOnlyErrorReply.Merge(m, src)
}
func (m *PartyActivityOnlyErrorReply) XXX_Size() int {
	return xxx_messageInfo_PartyActivityOnlyErrorReply.Size(m)
}
func (m *PartyActivityOnlyErrorReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PartyActivityOnlyErrorReply.DiscardUnknown(m)
}

var xxx_messageInfo_PartyActivityOnlyErrorReply proto.InternalMessageInfo

func (m *PartyActivityOnlyErrorReply) GetError() *ErrorDescription {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*ErrorDescription)(nil), "activities_v1.ErrorDescription")
	proto.RegisterMapType((map[string]string)(nil), "activities_v1.ErrorDescription.DetailsEntry")
	proto.RegisterType((*PagingParams)(nil), "activities_v1.PagingParams")
	proto.RegisterType((*Reference)(nil), "activities_v1.Reference")
	proto.RegisterType((*PartyActivity)(nil), "activities_v1.PartyActivity")
	proto.RegisterMapType((map[string]string)(nil), "activities_v1.PartyActivity.DetailsEntry")
	proto.RegisterType((*PartyActivityPage)(nil), "activities_v1.PartyActivityPage")
	proto.RegisterType((*PartyActivityPageRequest)(nil), "activities_v1.PartyActivityPageRequest")
	proto.RegisterMapType((map[string]string)(nil), "activities_v1.PartyActivityPageRequest.FilterEntry")
	proto.RegisterType((*PartyActivityPageReply)(nil), "activities_v1.PartyActivityPageReply")
	proto.RegisterType((*PartyActivityLogRequest)(nil), "activities_v1.PartyActivityLogRequest")
	proto.RegisterType((*PartyActivityObjectReply)(nil), "activities_v1.PartyActivityObjectReply")
	proto.RegisterType((*PartyActivityBatchRequest)(nil), "activities_v1.PartyActivityBatchRequest")
	proto.RegisterType((*PartyActivityDeleteRequest)(nil), "activities_v1.PartyActivityDeleteRequest")
	proto.RegisterMapType((map[string]string)(nil), "activities_v1.PartyActivityDeleteRequest.FilterEntry")
	proto.RegisterType((*PartyActivityOnlyErrorReply)(nil), "activities_v1.PartyActivityOnlyErrorReply")
}

func init() { proto.RegisterFile("protos/activities_v1.proto", fileDescriptor_9682ce189d08eec3) }

var fileDescriptor_9682ce189d08eec3 = []byte{
	// 884 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xae, 0x9d, 0x9f, 0x26, 0x27, 0xdb, 0xd5, 0x76, 0xb4, 0x74, 0x4d, 0x16, 0x69, 0x2b, 0x4b,
	0xbb, 0x74, 0x11, 0x04, 0x9a, 0x52, 0x69, 0x77, 0xc5, 0x4d, 0xff, 0x56, 0x8a, 0xd8, 0x15, 0x91,
	0xa9, 0x2a, 0x01, 0x17, 0xd1, 0xd4, 0x3e, 0xf1, 0x0e, 0x75, 0x6c, 0x33, 0x33, 0x89, 0x64, 0xae,
	0xb8, 0xe1, 0x8a, 0xb7, 0xe0, 0x21, 0x78, 0x03, 0x2e, 0x79, 0x11, 0x1e, 0x02, 0xa1, 0x99, 0xf1,
	0x26, 0x76, 0x1a, 0xdc, 0x86, 0xde, 0xcd, 0x9c, 0x9f, 0xef, 0x1c, 0x7f, 0xe7, 0x3b, 0x23, 0x43,
	0x37, 0xe5, 0x89, 0x4c, 0xc4, 0xe7, 0xd4, 0x97, 0x6c, 0xc6, 0x24, 0x43, 0x31, 0x9a, 0xed, 0xf7,
	0xb4, 0x91, 0x6c, 0x95, 0x8c, 0xee, 0xdf, 0x36, 0x3c, 0x38, 0xe3, 0x3c, 0xe1, 0xa7, 0x28, 0x7c,
	0xce, 0x52, 0xc9, 0x92, 0x98, 0x10, 0xa8, 0xcb, 0x2c, 0x45, 0xc7, 0xda, 0xb5, 0xf6, 0xda, 0x9e,
	0x3e, 0x93, 0x2e, 0xb4, 0x7c, 0x2a, 0x31, 0x4c, 0x78, 0xe6, 0xd8, 0xda, 0x3e, 0xbf, 0xab, 0x78,
	0x3f, 0x09, 0xd0, 0xa9, 0x99, 0x78, 0x75, 0x26, 0x4f, 0xe1, 0xbe, 0x9f, 0x70, 0x8e, 0x11, 0x55,
	0x90, 0x23, 0x16, 0x38, 0x75, 0xed, 0xdd, 0x2a, 0x58, 0x07, 0x01, 0xd9, 0x81, 0xa6, 0x90, 0x54,
	0x4e, 0x85, 0xd3, 0xd0, 0xee, 0xfc, 0x46, 0x1c, 0xd8, 0x9c, 0xa0, 0x10, 0x34, 0x44, 0xa7, 0xa9,
	0x1d, 0xef, 0xaf, 0xe4, 0x21, 0x34, 0x7c, 0x3a, 0x15, 0xe8, 0x6c, 0x6a, 0xbb, 0xb9, 0x90, 0x27,
	0xd0, 0x11, 0x92, 0xfa, 0x57, 0x23, 0xc9, 0xa9, 0x8f, 0x4e, 0x4b, 0xfb, 0x40, 0x9b, 0xce, 0x95,
	0x85, 0xbc, 0x86, 0xcd, 0x00, 0x25, 0x65, 0x91, 0x70, 0xda, 0xbb, 0xb5, 0xbd, 0x4e, 0xff, 0xd3,
	0x5e, 0x99, 0x9e, 0x65, 0x16, 0x7a, 0xa7, 0x26, 0xfc, 0x2c, 0x96, 0x3c, 0xf3, 0xde, 0x27, 0x77,
	0x5f, 0xc1, 0xbd, 0xa2, 0x83, 0x3c, 0x80, 0xda, 0x15, 0x66, 0x39, 0x55, 0xea, 0xa8, 0x1a, 0x9c,
	0xd1, 0x68, 0x8a, 0x39, 0x4d, 0xe6, 0xf2, 0xca, 0x7e, 0x61, 0xb9, 0x6f, 0xe0, 0xde, 0x90, 0x86,
	0x2c, 0x0e, 0x87, 0x94, 0xd3, 0x89, 0x50, 0xbc, 0x89, 0x2b, 0x96, 0xea, 0xe4, 0x9a, 0xa7, 0xcf,
	0x9a, 0x7b, 0x7a, 0x65, 0x92, 0x1b, 0x9e, 0x3e, 0x2b, 0x44, 0x99, 0x48, 0x1a, 0x69, 0x82, 0x5b,
	0x9e, 0xb9, 0xb8, 0x27, 0xd0, 0xf6, 0x70, 0x8c, 0x1c, 0x63, 0x1f, 0xc9, 0x7d, 0xb0, 0x59, 0x90,
	0x77, 0x61, 0xb3, 0x60, 0x3e, 0x42, 0xbb, 0x30, 0x42, 0x02, 0xf5, 0x98, 0x4e, 0xe6, 0x63, 0x52,
	0x67, 0xf7, 0x8f, 0x1a, 0x6c, 0x0d, 0x29, 0x97, 0xd9, 0x91, 0x21, 0x23, 0x5b, 0x89, 0xc4, 0x26,
	0x0b, 0x24, 0x36, 0xc1, 0x39, 0x7a, 0xad, 0x80, 0xde, 0x83, 0x46, 0xaa, 0x80, 0xf4, 0x9c, 0x3b,
	0x7d, 0x67, 0x89, 0xde, 0x79, 0xab, 0x9e, 0x09, 0x23, 0x07, 0xd0, 0xe2, 0x38, 0x1e, 0x31, 0x89,
	0x13, 0x3d, 0xfb, 0xaa, 0x94, 0x4d, 0x8e, 0xe3, 0x81, 0xc4, 0x09, 0x79, 0x09, 0x1d, 0x95, 0x94,
	0x52, 0x8e, 0xb1, 0x14, 0x4e, 0x53, 0x4f, 0xf2, 0xbf, 0xf3, 0x80, 0xe3, 0x78, 0x68, 0x62, 0xc9,
	0x21, 0xb4, 0xf3, 0x54, 0x99, 0x69, 0xed, 0x54, 0x25, 0xb6, 0x4c, 0xa2, 0xcc, 0xc8, 0xc9, 0x42,
	0x37, 0x2d, 0x5d, 0xed, 0xf9, 0x52, 0x52, 0x89, 0xbd, 0xd5, 0xa2, 0x21, 0x1f, 0x40, 0x33, 0xe1,
	0xa1, 0x5a, 0x82, 0xb6, 0xd1, 0x44, 0xc2, 0xc3, 0x41, 0x70, 0x27, 0x2d, 0xfd, 0x00, 0xdb, 0xa5,
	0xca, 0xc3, 0x7c, 0x37, 0x8c, 0x50, 0x8c, 0xa2, 0xcc, 0x85, 0x7c, 0x01, 0xf5, 0x80, 0x4a, 0xea,
	0xd8, 0xba, 0xff, 0x8f, 0xaa, 0xfa, 0xf7, 0x74, 0xa4, 0xfb, 0x8f, 0x05, 0xce, 0x35, 0x74, 0x0f,
	0x7f, 0x9a, 0xa2, 0x90, 0x2b, 0x36, 0xdb, 0x5a, 0xb5, 0xd9, 0x5f, 0x43, 0x73, 0xcc, 0x22, 0x89,
	0x3c, 0xaf, 0x7b, 0x50, 0x55, 0xb7, 0x80, 0xdf, 0x7b, 0xad, 0xb3, 0x0c, 0x83, 0x39, 0x04, 0x39,
	0x80, 0x66, 0xaa, 0x37, 0x47, 0x4b, 0xae, 0xd3, 0x7f, 0x7c, 0x0d, 0x6c, 0xb1, 0x56, 0x5e, 0x1e,
	0xda, 0x7d, 0x09, 0x9d, 0x02, 0xd6, 0x5a, 0xec, 0xfe, 0x6a, 0xc1, 0xce, 0x8a, 0x06, 0xd3, 0x28,
	0x23, 0x87, 0xd0, 0x40, 0xf5, 0x54, 0x68, 0xa0, 0x4e, 0xff, 0xc9, 0x0d, 0xcf, 0x88, 0x67, 0xa2,
	0xc9, 0x97, 0x50, 0x4f, 0xd5, 0x6b, 0x66, 0xeb, 0xac, 0xdd, 0x1b, 0xc9, 0xd0, 0xd1, 0xee, 0xcf,
	0xf0, 0xa8, 0xe4, 0x7a, 0x93, 0x84, 0x6b, 0x8e, 0xe1, 0x05, 0xb4, 0xf2, 0x52, 0x59, 0x5e, 0xbb,
	0x5a, 0x00, 0xf3, 0x68, 0xf7, 0xb7, 0x65, 0x11, 0x7c, 0x73, 0xf9, 0x23, 0xfa, 0xf2, 0x4e, 0x2c,
	0xfc, 0xff, 0x6e, 0x7e, 0xb1, 0xe0, 0xc3, 0x92, 0xef, 0x98, 0x4a, 0xff, 0xdd, 0x9a, 0x64, 0x7c,
	0x05, 0xb0, 0xa8, 0x76, 0xab, 0x7d, 0x28, 0xc4, 0xbb, 0x7f, 0x59, 0xd0, 0x2d, 0x79, 0x4f, 0x31,
	0x42, 0xb9, 0xee, 0x5e, 0xbc, 0x5d, 0xda, 0x8b, 0xc3, 0xaa, 0xfa, 0xa5, 0x0a, 0xab, 0x36, 0xe3,
	0x2e, 0x22, 0x3f, 0x87, 0xc7, 0xe5, 0xf9, 0xc6, 0x51, 0xa6, 0x07, 0x77, 0x97, 0x11, 0xf7, 0xff,
	0xac, 0x01, 0x1c, 0xcd, 0x23, 0xc9, 0x3b, 0x78, 0x18, 0xa2, 0x34, 0xcf, 0xee, 0x68, 0x81, 0x40,
	0x3e, 0xbe, 0xe5, 0x73, 0xd0, 0x7d, 0x7a, 0x73, 0x60, 0x1a, 0x65, 0xee, 0x06, 0x09, 0x81, 0x44,
	0x49, 0x58, 0xae, 0x94, 0x91, 0x67, 0x55, 0xe9, 0x8b, 0x75, 0xea, 0x56, 0xf6, 0x53, 0x50, 0xbe,
	0xbb, 0x41, 0x52, 0xd8, 0xb9, 0x54, 0xe2, 0xbb, 0xfe, 0x51, 0x7b, 0x55, 0x20, 0x45, 0xc1, 0x76,
	0x3f, 0xa9, 0x2c, 0x57, 0x1a, 0x84, 0xbb, 0x41, 0x38, 0x3c, 0x0a, 0xb4, 0x12, 0xae, 0x97, 0x7c,
	0x7e, 0x6b, 0xf9, 0xac, 0x57, 0xf3, 0xf8, 0x3b, 0x78, 0x96, 0xb2, 0xf4, 0x33, 0x81, 0x7c, 0xc6,
	0x7c, 0x14, 0xbd, 0xa9, 0x40, 0x2e, 0x0a, 0x08, 0xbd, 0x19, 0x72, 0xc1, 0x92, 0x78, 0xff, 0x78,
	0x7b, 0x31, 0xee, 0xa1, 0xfa, 0xc7, 0xbc, 0xd8, 0x1f, 0x5a, 0xdf, 0x37, 0xcd, 0x3f, 0xe8, 0xef,
	0xf6, 0xf6, 0xd1, 0xc9, 0xf9, 0xe0, 0x62, 0x70, 0x3e, 0x38, 0xfb, 0x76, 0x74, 0xf2, 0xf6, 0x74,
	0x74, 0xb1, 0x7f, 0x69, 0x7c, 0x07, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xba, 0xdc, 0x25, 0x94,
	0xa8, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ActivitiesClient is the client API for Activities service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ActivitiesClient interface {
	GetPartyActivities(ctx context.Context, in *PartyActivityPageRequest, opts ...grpc.CallOption) (*PartyActivityPageReply, error)
	LogPartyActivity(ctx context.Context, in *PartyActivityLogRequest, opts ...grpc.CallOption) (*PartyActivityObjectReply, error)
	BatchPartyActivities(ctx context.Context, in *PartyActivityBatchRequest, opts ...grpc.CallOption) (*PartyActivityOnlyErrorReply, error)
	DeletePartyActivities(ctx context.Context, in *PartyActivityDeleteRequest, opts ...grpc.CallOption) (*PartyActivityOnlyErrorReply, error)
}

type activitiesClient struct {
	cc *grpc.ClientConn
}

func NewActivitiesClient(cc *grpc.ClientConn) ActivitiesClient {
	return &activitiesClient{cc}
}

func (c *activitiesClient) GetPartyActivities(ctx context.Context, in *PartyActivityPageRequest, opts ...grpc.CallOption) (*PartyActivityPageReply, error) {
	out := new(PartyActivityPageReply)
	err := c.cc.Invoke(ctx, "/activities_v1.Activities/get_party_activities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitiesClient) LogPartyActivity(ctx context.Context, in *PartyActivityLogRequest, opts ...grpc.CallOption) (*PartyActivityObjectReply, error) {
	out := new(PartyActivityObjectReply)
	err := c.cc.Invoke(ctx, "/activities_v1.Activities/log_party_activity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitiesClient) BatchPartyActivities(ctx context.Context, in *PartyActivityBatchRequest, opts ...grpc.CallOption) (*PartyActivityOnlyErrorReply, error) {
	out := new(PartyActivityOnlyErrorReply)
	err := c.cc.Invoke(ctx, "/activities_v1.Activities/batch_party_activities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitiesClient) DeletePartyActivities(ctx context.Context, in *PartyActivityDeleteRequest, opts ...grpc.CallOption) (*PartyActivityOnlyErrorReply, error) {
	out := new(PartyActivityOnlyErrorReply)
	err := c.cc.Invoke(ctx, "/activities_v1.Activities/delete_party_activities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivitiesServer is the server API for Activities service.
type ActivitiesServer interface {
	GetPartyActivities(context.Context, *PartyActivityPageRequest) (*PartyActivityPageReply, error)
	LogPartyActivity(context.Context, *PartyActivityLogRequest) (*PartyActivityObjectReply, error)
	BatchPartyActivities(context.Context, *PartyActivityBatchRequest) (*PartyActivityOnlyErrorReply, error)
	DeletePartyActivities(context.Context, *PartyActivityDeleteRequest) (*PartyActivityOnlyErrorReply, error)
}

// UnimplementedActivitiesServer can be embedded to have forward compatible implementations.
type UnimplementedActivitiesServer struct {
}

func (*UnimplementedActivitiesServer) GetPartyActivities(ctx context.Context, req *PartyActivityPageRequest) (*PartyActivityPageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPartyActivities not implemented")
}
func (*UnimplementedActivitiesServer) LogPartyActivity(ctx context.Context, req *PartyActivityLogRequest) (*PartyActivityObjectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogPartyActivity not implemented")
}
func (*UnimplementedActivitiesServer) BatchPartyActivities(ctx context.Context, req *PartyActivityBatchRequest) (*PartyActivityOnlyErrorReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchPartyActivities not implemented")
}
func (*UnimplementedActivitiesServer) DeletePartyActivities(ctx context.Context, req *PartyActivityDeleteRequest) (*PartyActivityOnlyErrorReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePartyActivities not implemented")
}

func RegisterActivitiesServer(s *grpc.Server, srv ActivitiesServer) {
	s.RegisterService(&_Activities_serviceDesc, srv)
}

func _Activities_GetPartyActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartyActivityPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitiesServer).GetPartyActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activities_v1.Activities/GetPartyActivities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitiesServer).GetPartyActivities(ctx, req.(*PartyActivityPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activities_LogPartyActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartyActivityLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitiesServer).LogPartyActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activities_v1.Activities/LogPartyActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitiesServer).LogPartyActivity(ctx, req.(*PartyActivityLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activities_BatchPartyActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartyActivityBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitiesServer).BatchPartyActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activities_v1.Activities/BatchPartyActivities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitiesServer).BatchPartyActivities(ctx, req.(*PartyActivityBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activities_DeletePartyActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartyActivityDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitiesServer).DeletePartyActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activities_v1.Activities/DeletePartyActivities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitiesServer).DeletePartyActivities(ctx, req.(*PartyActivityDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Activities_serviceDesc = grpc.ServiceDesc{
	ServiceName: "activities_v1.Activities",
	HandlerType: (*ActivitiesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "get_party_activities",
			Handler:    _Activities_GetPartyActivities_Handler,
		},
		{
			MethodName: "log_party_activity",
			Handler:    _Activities_LogPartyActivity_Handler,
		},
		{
			MethodName: "batch_party_activities",
			Handler:    _Activities_BatchPartyActivities_Handler,
		},
		{
			MethodName: "delete_party_activities",
			Handler:    _Activities_DeletePartyActivities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/activities_v1.proto",
}
